let json = 
{
	"responseData": [
			{
				"name": "热门城市",
				"selected": "0",
				"son": [{
					"id": "1",
					"name": "北京",
					"value_cnt": "12676",
					"pinyin": "beijing",
					"selected": "0"
				}, {
					"id": "385",
					"name": "成都",
					"value_cnt": "6715",
					"pinyin": "chengdu",
					"selected": "0"
				}, {
					"id": "9",
					"name": "上海",
					"value_cnt": "6172",
					"pinyin": "shanghai",
					"selected": "0"
				}, {
					"id": "291",
					"name": "深圳",
					"value_cnt": "5686",
					"pinyin": "shenzhen",
					"selected": "0"
				}, {
					"id": "289",
					"name": "广州",
					"value_cnt": "5428",
					"pinyin": "guangzhou",
					"selected": "0"
				}, {
					"id": "22",
					"name": "重庆",
					"value_cnt": "5213",
					"pinyin": "chongqing",
					"selected": "0"
				}, {
					"id": "175",
					"name": "杭州",
					"value_cnt": "3238",
					"pinyin": "hangzhou",
					"selected": "0"
				}, {
					"id": "162",
					"name": "南京",
					"value_cnt": "2479",
					"pinyin": "nanjing",
					"selected": "0"
				}, {
					"id": "166",
					"name": "苏州",
					"value_cnt": "1630",
					"pinyin": "suzhou166",
					"selected": "0"
				}, {
					"id": "186",
					"name": "合肥",
					"value_cnt": "1584",
					"pinyin": "hefei",
					"selected": "0"
				}]
			}, {
				"id": "0",
				"name": "全部城市",
				"selected": "1",
				"letter": "Q",
				"pinyin": "quanguo",
				"first_letters": "Qg",
				"allname": "全部城市",
				"son": [{
					"id": "0",
					"name": "全部城市",
					"selected": "1",
					"letter": "Q",
					"pinyin": "quanguo",
					"first_letters": "Qg",
					"allname": "全部城市",
					"son": []
				}]
			}, {
				"id": "1",
				"name": "北京",
				"letter": "B",
				"pinyin": "beijing",
				"first_letters": "BJS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "北京市",
				"son": [{
					"id": "1",
					"name": "北京市",
					"letter": "B",
					"pinyin": "beijing",
					"first_letters": "BJS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "北京市"
				}]
			}, {
				"id": "9",
				"name": "上海",
				"letter": "S",
				"pinyin": "shanghai",
				"first_letters": "SHS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "上海市",
				"son": [{
					"id": "9",
					"name": "上海市",
					"letter": "S",
					"pinyin": "shanghai",
					"first_letters": "SHS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "上海市"
				}]
			}, {
				"id": "2",
				"name": "天津",
				"letter": "T",
				"pinyin": "tianjin",
				"first_letters": "TJS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "天津市",
				"son": [{
					"id": "2",
					"name": "天津市",
					"letter": "T",
					"pinyin": "tianjin",
					"first_letters": "TJS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "天津市"
				}]
			}, {
				"id": "22",
				"name": "重庆",
				"letter": "C",
				"pinyin": "chongqing",
				"first_letters": "CQS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "重庆市",
				"son": [{
					"id": "22",
					"name": "重庆市",
					"letter": "C",
					"pinyin": "chongqing",
					"first_letters": "CQS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "重庆市"
				}]
			}, {
				"id": "19",
				"name": "广东",
				"letter": "G",
				"pinyin": "guangdong",
				"first_letters": "GDS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "广东省",
				"son": [{
					"id": "19",
					"name": "广东省",
					"letter": "G",
					"pinyin": "guangdong",
					"first_letters": "GDS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "广东省"
				}, {
					"id": "289",
					"name": "广州市",
					"letter": "G",
					"pinyin": "guangzhou",
					"first_letters": "GZS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "290",
					"name": "韶关市",
					"letter": "S",
					"pinyin": "shaoguan",
					"first_letters": "SGS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "291",
					"name": "深圳市",
					"letter": "S",
					"pinyin": "shenzhen",
					"first_letters": "SZS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "305",
					"name": "东莞市",
					"letter": "D",
					"pinyin": "dongguan",
					"first_letters": "DGS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "306",
					"name": "中山市",
					"letter": "Z",
					"pinyin": "zhongshan",
					"first_letters": "ZSS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "292",
					"name": "珠海市",
					"letter": "Z",
					"pinyin": "zhuhai",
					"first_letters": "ZHS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "294",
					"name": "佛山市",
					"letter": "F",
					"pinyin": "foshan",
					"first_letters": "FSS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "293",
					"name": "汕头市",
					"letter": "S",
					"pinyin": "shantou",
					"first_letters": "STS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "295",
					"name": "江门市",
					"letter": "J",
					"pinyin": "jiangmen",
					"first_letters": "JMS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "296",
					"name": "湛江市",
					"letter": "Z",
					"pinyin": "zhanjiang",
					"first_letters": "ZJS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "297",
					"name": "茂名市",
					"letter": "M",
					"pinyin": "maoming",
					"first_letters": "MMS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "298",
					"name": "肇庆市",
					"letter": "Z",
					"pinyin": "zhaoqing",
					"first_letters": "ZQS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "299",
					"name": "惠州市",
					"letter": "H",
					"pinyin": "huizhou",
					"first_letters": "HZS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "300",
					"name": "梅州市",
					"letter": "M",
					"pinyin": "meizhou",
					"first_letters": "MZS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "301",
					"name": "汕尾市",
					"letter": "S",
					"pinyin": "shanwei",
					"first_letters": "SWS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "302",
					"name": "河源市",
					"letter": "H",
					"pinyin": "heyuan",
					"first_letters": "HYS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "303",
					"name": "阳江市",
					"letter": "Y",
					"pinyin": "yangjiang",
					"first_letters": "YJS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "304",
					"name": "清远市",
					"letter": "Q",
					"pinyin": "qingyuan",
					"first_letters": "QYS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "307",
					"name": "潮州市",
					"letter": "C",
					"pinyin": "chaozhou",
					"first_letters": "CZS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "308",
					"name": "揭阳市",
					"letter": "J",
					"pinyin": "jieyang",
					"first_letters": "JYS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}, {
					"id": "309",
					"name": "云浮市",
					"letter": "Y",
					"pinyin": "yunfu",
					"first_letters": "YFS",
					"upid": "19",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "11",
				"name": "浙江",
				"letter": "Z",
				"pinyin": "zhejiang",
				"first_letters": "ZJS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "浙江省",
				"son": [{
					"id": "11",
					"name": "浙江省",
					"letter": "Z",
					"pinyin": "zhejiang",
					"first_letters": "ZJS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "浙江省"
				}, {
					"id": "175",
					"name": "杭州市",
					"letter": "H",
					"pinyin": "hangzhou",
					"first_letters": "HZS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "176",
					"name": "宁波市",
					"letter": "N",
					"pinyin": "ningbo",
					"first_letters": "NBS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "177",
					"name": "温州市",
					"letter": "W",
					"pinyin": "wenzhou",
					"first_letters": "WZS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "178",
					"name": "嘉兴市",
					"letter": "J",
					"pinyin": "jiaxing",
					"first_letters": "JXS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "183",
					"name": "金华市",
					"letter": "J",
					"pinyin": "jinhua",
					"first_letters": "JHS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "184",
					"name": "台州市",
					"letter": "T",
					"pinyin": "taizhou184",
					"first_letters": "TZS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "179",
					"name": "湖州市",
					"letter": "H",
					"pinyin": "huzhou",
					"first_letters": "HZS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "180",
					"name": "绍兴市",
					"letter": "S",
					"pinyin": "shaoxing",
					"first_letters": "SXS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "181",
					"name": "舟山市",
					"letter": "Z",
					"pinyin": "zhoushan",
					"first_letters": "ZSS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "182",
					"name": "衢州市",
					"letter": "",
					"pinyin": "quzhou182",
					"first_letters": "ZS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}, {
					"id": "185",
					"name": "丽水市",
					"letter": "L",
					"pinyin": "lishui",
					"first_letters": "LSS",
					"upid": "11",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "23",
				"name": "四川",
				"letter": "S",
				"pinyin": "sichuan",
				"first_letters": "SCS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "四川省",
				"son": [{
					"id": "23",
					"name": "四川省",
					"letter": "S",
					"pinyin": "sichuan",
					"first_letters": "SCS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "四川省"
				}, {
					"id": "385",
					"name": "成都市",
					"letter": "C",
					"pinyin": "chengdu",
					"first_letters": "CDS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "386",
					"name": "自贡市",
					"letter": "Z",
					"pinyin": "zigong",
					"first_letters": "ZGS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "390",
					"name": "绵阳市",
					"letter": "M",
					"pinyin": "mianyang",
					"first_letters": "MYS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "389",
					"name": "德阳市",
					"letter": "D",
					"pinyin": "deyang",
					"first_letters": "DYS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "394",
					"name": "乐山市",
					"letter": "L",
					"pinyin": "leshan",
					"first_letters": "LSS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "395",
					"name": "南充市",
					"letter": "N",
					"pinyin": "nanchong",
					"first_letters": "NCS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "387",
					"name": "攀枝花市",
					"letter": "P",
					"pinyin": "panzhihua",
					"first_letters": "PZHS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "388",
					"name": "泸州市",
					"letter": "",
					"pinyin": "luzhou388",
					"first_letters": "ZS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "391",
					"name": "广元市",
					"letter": "G",
					"pinyin": "guangyuan",
					"first_letters": "GYS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "392",
					"name": "遂宁市",
					"letter": "S",
					"pinyin": "suining",
					"first_letters": "SNS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "393",
					"name": "内江市",
					"letter": "N",
					"pinyin": "neijiang",
					"first_letters": "NJS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "396",
					"name": "眉山市",
					"letter": "M",
					"pinyin": "meishan",
					"first_letters": "MSS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "397",
					"name": "宜宾市",
					"letter": "Y",
					"pinyin": "yibin",
					"first_letters": "YBS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "398",
					"name": "广安市",
					"letter": "G",
					"pinyin": "guangan",
					"first_letters": "GAS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "399",
					"name": "达州市",
					"letter": "D",
					"pinyin": "dazhou",
					"first_letters": "DZS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "400",
					"name": "雅安市",
					"letter": "Y",
					"pinyin": "yaan",
					"first_letters": "YAS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "401",
					"name": "巴中市",
					"letter": "B",
					"pinyin": "bazhong",
					"first_letters": "BZS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "402",
					"name": "资阳市",
					"letter": "Z",
					"pinyin": "ziyang",
					"first_letters": "ZYS",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "403",
					"name": "阿坝藏族羌族自治州",
					"letter": "A",
					"pinyin": "aba",
					"first_letters": "ABCZQZZZZ",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}, {
					"id": "405",
					"name": "凉山彝族自治州",
					"letter": "L",
					"pinyin": "liangshan",
					"first_letters": "LSYZZZZ",
					"upid": "23",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "10",
				"name": "江苏",
				"letter": "J",
				"pinyin": "jiangsu",
				"first_letters": "JSS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "江苏省",
				"son": [{
					"id": "10",
					"name": "江苏省",
					"letter": "J",
					"pinyin": "jiangsu",
					"first_letters": "JSS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "江苏省"
				}, {
					"id": "162",
					"name": "南京市",
					"letter": "N",
					"pinyin": "nanjing",
					"first_letters": "NJS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "166",
					"name": "苏州市",
					"letter": "S",
					"pinyin": "suzhou166",
					"first_letters": "SZS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "163",
					"name": "无锡市",
					"letter": "W",
					"pinyin": "wuxi",
					"first_letters": "WXS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "165",
					"name": "常州市",
					"letter": "C",
					"pinyin": "changzhou",
					"first_letters": "CZS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "167",
					"name": "南通市",
					"letter": "N",
					"pinyin": "nantong",
					"first_letters": "NTS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "170",
					"name": "盐城市",
					"letter": "Y",
					"pinyin": "yancheng",
					"first_letters": "YCS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "164",
					"name": "徐州市",
					"letter": "X",
					"pinyin": "xuzhou",
					"first_letters": "XZS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "168",
					"name": "连云港市",
					"letter": "L",
					"pinyin": "lianyungang",
					"first_letters": "LYGS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "171",
					"name": "扬州市",
					"letter": "Y",
					"pinyin": "yangzhou",
					"first_letters": "YZS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "169",
					"name": "淮安市",
					"letter": "H",
					"pinyin": "huaian",
					"first_letters": "HAS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "172",
					"name": "镇江市",
					"letter": "Z",
					"pinyin": "zhenjiang",
					"first_letters": "ZJS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "173",
					"name": "泰州市",
					"letter": "T",
					"pinyin": "taizhou173",
					"first_letters": "TZS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}, {
					"id": "174",
					"name": "宿迁市",
					"letter": "S",
					"pinyin": "suqian",
					"first_letters": "SQS",
					"upid": "10",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "16",
				"name": "河南",
				"letter": "H",
				"pinyin": "henan",
				"first_letters": "HNS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "河南省",
				"son": [{
					"id": "16",
					"name": "河南省",
					"letter": "H",
					"pinyin": "henan",
					"first_letters": "HNS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "河南省"
				}, {
					"id": "240",
					"name": "郑州市",
					"letter": "Z",
					"pinyin": "zhengzhou",
					"first_letters": "ZZS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "241",
					"name": "开封市",
					"letter": "K",
					"pinyin": "kaifeng",
					"first_letters": "KFS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "242",
					"name": "洛阳市",
					"letter": "L",
					"pinyin": "luoyang",
					"first_letters": "LYS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "243",
					"name": "平顶山市",
					"letter": "P",
					"pinyin": "pingdingshan",
					"first_letters": "PDSS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "244",
					"name": "安阳市",
					"letter": "A",
					"pinyin": "anyang",
					"first_letters": "AYS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "245",
					"name": "鹤壁市",
					"letter": "H",
					"pinyin": "hebi",
					"first_letters": "HBS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "246",
					"name": "新乡市",
					"letter": "X",
					"pinyin": "xinxiang",
					"first_letters": "XXS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "247",
					"name": "焦作市",
					"letter": "J",
					"pinyin": "jiaozuo",
					"first_letters": "JZS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "248",
					"name": "濮阳市",
					"letter": "P",
					"pinyin": "puyang",
					"first_letters": "YS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "249",
					"name": "许昌市",
					"letter": "X",
					"pinyin": "xuchang",
					"first_letters": "XCS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "250",
					"name": "漯河市",
					"letter": "",
					"pinyin": "luohe",
					"first_letters": "HS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "251",
					"name": "三门峡市",
					"letter": "S",
					"pinyin": "sanmenxia",
					"first_letters": "SMXS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "252",
					"name": "南阳市",
					"letter": "N",
					"pinyin": "nanyang",
					"first_letters": "NYS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "253",
					"name": "商丘市",
					"letter": "S",
					"pinyin": "shangqiu",
					"first_letters": "SQS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "254",
					"name": "信阳市",
					"letter": "X",
					"pinyin": "xinyang",
					"first_letters": "XYS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "255",
					"name": "周口市",
					"letter": "Z",
					"pinyin": "zhoukou",
					"first_letters": "ZKS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "256",
					"name": "驻马店市",
					"letter": "Z",
					"pinyin": "zhumadian",
					"first_letters": "ZMDS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}, {
					"id": "257",
					"name": "济源市",
					"letter": "J",
					"pinyin": "jiyuan",
					"first_letters": "JYS",
					"upid": "16",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "17",
				"name": "湖北",
				"letter": "H",
				"pinyin": "hubei",
				"first_letters": "HBS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "湖北省",
				"son": [{
					"id": "17",
					"name": "湖北省",
					"letter": "H",
					"pinyin": "hubei",
					"first_letters": "HBS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "湖北省"
				}, {
					"id": "258",
					"name": "武汉市",
					"letter": "W",
					"pinyin": "wuhan",
					"first_letters": "WHS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "259",
					"name": "黄石市",
					"letter": "H",
					"pinyin": "huangshi",
					"first_letters": "HSS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "266",
					"name": "荆州市",
					"letter": "J",
					"pinyin": "jingzhou",
					"first_letters": "JZS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "261",
					"name": "宜昌市",
					"letter": "Y",
					"pinyin": "yichang",
					"first_letters": "YCS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "45068",
					"name": "襄阳市",
					"letter": "X",
					"pinyin": "xiangyang",
					"first_letters": "XYS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "273",
					"name": "天门市",
					"letter": "T",
					"pinyin": "tianmen",
					"first_letters": "TMS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "260",
					"name": "十堰市",
					"letter": "S",
					"pinyin": "shiyan",
					"first_letters": "SYS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "262",
					"name": "襄樊市",
					"letter": "X",
					"pinyin": "xiangfan",
					"first_letters": "XFS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "263",
					"name": "鄂州市",
					"letter": "E",
					"pinyin": "ezhou",
					"first_letters": "EZS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "264",
					"name": "荆门市",
					"letter": "J",
					"pinyin": "jingmen",
					"first_letters": "JMS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "265",
					"name": "孝感市",
					"letter": "X",
					"pinyin": "xiaogan",
					"first_letters": "XGS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "267",
					"name": "黄冈市",
					"letter": "H",
					"pinyin": "huanggang",
					"first_letters": "HGS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "268",
					"name": "咸宁市",
					"letter": "X",
					"pinyin": "xianning",
					"first_letters": "XNS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "269",
					"name": "随州市",
					"letter": "S",
					"pinyin": "suizhou",
					"first_letters": "SZS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "270",
					"name": "恩施土家族苗族自治州",
					"letter": "E",
					"pinyin": "enshi2",
					"first_letters": "ESTJZMZZZZ",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "271",
					"name": "仙桃市",
					"letter": "X",
					"pinyin": "xiantao",
					"first_letters": "XTS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}, {
					"id": "272",
					"name": "潜江市",
					"letter": "Q",
					"pinyin": "qianjiang",
					"first_letters": "QJS",
					"upid": "17",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "18",
				"name": "湖南",
				"letter": "H",
				"pinyin": "hunan",
				"first_letters": "HNS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "湖南省",
				"son": [{
					"id": "18",
					"name": "湖南省",
					"letter": "H",
					"pinyin": "hunan",
					"first_letters": "HNS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "湖南省"
				}, {
					"id": "275",
					"name": "长沙市",
					"letter": "C",
					"pinyin": "changsha",
					"first_letters": "CSS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "276",
					"name": "株洲市",
					"letter": "Z",
					"pinyin": "zhuzhou",
					"first_letters": "ZZS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "278",
					"name": "衡阳市",
					"letter": "H",
					"pinyin": "hengyang",
					"first_letters": "HYS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "283",
					"name": "益阳市",
					"letter": "Y",
					"pinyin": "yiyang",
					"first_letters": "YYS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "279",
					"name": "邵阳市",
					"letter": "S",
					"pinyin": "shaoyang",
					"first_letters": "SYS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "277",
					"name": "湘潭市",
					"letter": "X",
					"pinyin": "xiangtan",
					"first_letters": "XTS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "280",
					"name": "岳阳市",
					"letter": "Y",
					"pinyin": "yueyang",
					"first_letters": "YYS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "281",
					"name": "常德市",
					"letter": "C",
					"pinyin": "changde",
					"first_letters": "CDS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "282",
					"name": "张家界市",
					"letter": "Z",
					"pinyin": "zhangjiajie",
					"first_letters": "ZJJS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "284",
					"name": "郴州市",
					"letter": "C",
					"pinyin": "chenzhou",
					"first_letters": "CZS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "285",
					"name": "永州市",
					"letter": "Y",
					"pinyin": "yongzhou",
					"first_letters": "YZS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "286",
					"name": "怀化市",
					"letter": "H",
					"pinyin": "huaihua",
					"first_letters": "HHS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "287",
					"name": "娄底市",
					"letter": "L",
					"pinyin": "loudi",
					"first_letters": "LDS",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}, {
					"id": "288",
					"name": "湘西土家族苗族自治州",
					"letter": "X",
					"pinyin": "xiangxi",
					"first_letters": "XXTJZMZZZZ",
					"upid": "18",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "15",
				"name": "山东",
				"letter": "S",
				"pinyin": "shandong",
				"first_letters": "SDS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "山东省",
				"son": [{
					"id": "15",
					"name": "山东省",
					"letter": "S",
					"pinyin": "shandong",
					"first_letters": "SDS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "山东省"
				}, {
					"id": "223",
					"name": "济南市",
					"letter": "J",
					"pinyin": "jinan",
					"first_letters": "JNS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "224",
					"name": "青岛市",
					"letter": "Q",
					"pinyin": "qingdao",
					"first_letters": "QDS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "226",
					"name": "枣庄市",
					"letter": "Z",
					"pinyin": "zaozhuang",
					"first_letters": "ZZS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "228",
					"name": "烟台市",
					"letter": "Y",
					"pinyin": "yantai",
					"first_letters": "YTS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "225",
					"name": "淄博市",
					"letter": "Z",
					"pinyin": "zibo",
					"first_letters": "ZBS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "235",
					"name": "临沂市",
					"letter": "L",
					"pinyin": "linyi",
					"first_letters": "LYS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "227",
					"name": "东营市",
					"letter": "D",
					"pinyin": "dongying",
					"first_letters": "DYS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "229",
					"name": "潍坊市",
					"letter": "W",
					"pinyin": "weifang",
					"first_letters": "WFS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "230",
					"name": "济宁市",
					"letter": "J",
					"pinyin": "jining",
					"first_letters": "JNS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "231",
					"name": "泰安市",
					"letter": "T",
					"pinyin": "taian",
					"first_letters": "TAS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "232",
					"name": "威海市",
					"letter": "W",
					"pinyin": "weihai",
					"first_letters": "WHS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "233",
					"name": "日照市",
					"letter": "R",
					"pinyin": "rizhao",
					"first_letters": "RZS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "236",
					"name": "德州市",
					"letter": "D",
					"pinyin": "dezhou",
					"first_letters": "DZS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "237",
					"name": "聊城市",
					"letter": "L",
					"pinyin": "liaocheng",
					"first_letters": "LCS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "238",
					"name": "滨州市",
					"letter": "B",
					"pinyin": "binzhou",
					"first_letters": "BZS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}, {
					"id": "239",
					"name": "菏泽市",
					"letter": "H",
					"pinyin": "heze",
					"first_letters": "HZS",
					"upid": "15",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "6",
				"name": "辽宁",
				"letter": "L",
				"pinyin": "liaoning",
				"first_letters": "LNS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "辽宁省",
				"son": [{
					"id": "6",
					"name": "辽宁省",
					"letter": "L",
					"pinyin": "liaoning",
					"first_letters": "LNS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "辽宁省"
				}, {
					"id": "107",
					"name": "沈阳市",
					"letter": "S",
					"pinyin": "shenyang",
					"first_letters": "SYS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "108",
					"name": "大连市",
					"letter": "D",
					"pinyin": "dalian",
					"first_letters": "DLS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "109",
					"name": "鞍山市",
					"letter": "A",
					"pinyin": "anshan",
					"first_letters": "ASS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "112",
					"name": "丹东市",
					"letter": "D",
					"pinyin": "dandong",
					"first_letters": "DDS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "113",
					"name": "锦州市",
					"letter": "J",
					"pinyin": "jinzhou",
					"first_letters": "JZS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "114",
					"name": "营口市",
					"letter": "Y",
					"pinyin": "yingkou",
					"first_letters": "YKS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "115",
					"name": "阜新市",
					"letter": "F",
					"pinyin": "fuxin",
					"first_letters": "FXS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "117",
					"name": "盘锦市",
					"letter": "P",
					"pinyin": "panjin",
					"first_letters": "PJS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "118",
					"name": "铁岭市",
					"letter": "T",
					"pinyin": "tieling",
					"first_letters": "TLS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "119",
					"name": "朝阳市",
					"letter": "C",
					"pinyin": "chaoyang",
					"first_letters": "CYS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}, {
					"id": "120",
					"name": "葫芦岛市",
					"letter": "H",
					"pinyin": "huludao",
					"first_letters": "HLDS",
					"upid": "6",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "13",
				"name": "福建",
				"letter": "F",
				"pinyin": "fujian",
				"first_letters": "FJS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "福建省",
				"son": [{
					"id": "13",
					"name": "福建省",
					"letter": "F",
					"pinyin": "fujian",
					"first_letters": "FJS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "福建省"
				}, {
					"id": "203",
					"name": "福州市",
					"letter": "F",
					"pinyin": "fuzhou203",
					"first_letters": "FZS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "204",
					"name": "厦门市",
					"letter": "X",
					"pinyin": "xiamen",
					"first_letters": "XMS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "205",
					"name": "莆田市",
					"letter": "P",
					"pinyin": "putian",
					"first_letters": "PTS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "206",
					"name": "三明市",
					"letter": "S",
					"pinyin": "sanming",
					"first_letters": "SMS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "207",
					"name": "泉州市",
					"letter": "Q",
					"pinyin": "quanzhou",
					"first_letters": "QZS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "208",
					"name": "漳州市",
					"letter": "Z",
					"pinyin": "zhangzhou",
					"first_letters": "ZZS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "209",
					"name": "南平市",
					"letter": "N",
					"pinyin": "nanping",
					"first_letters": "NPS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "210",
					"name": "龙岩市",
					"letter": "L",
					"pinyin": "longyan",
					"first_letters": "LYS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}, {
					"id": "211",
					"name": "宁德市",
					"letter": "N",
					"pinyin": "ningde",
					"first_letters": "NDS",
					"upid": "13",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "3",
				"name": "河北",
				"letter": "H",
				"pinyin": "hebei",
				"first_letters": "HBS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "河北省",
				"son": [{
					"id": "3",
					"name": "河北省",
					"letter": "H",
					"pinyin": "hebei",
					"first_letters": "HBS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "河北省"
				}, {
					"id": "73",
					"name": "石家庄市",
					"letter": "S",
					"pinyin": "shijiazhuang",
					"first_letters": "SJZS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "74",
					"name": "唐山市",
					"letter": "T",
					"pinyin": "tangshan",
					"first_letters": "TSS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "75",
					"name": "秦皇岛市",
					"letter": "Q",
					"pinyin": "qinhuangdao",
					"first_letters": "QHDS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "76",
					"name": "邯郸市",
					"letter": "H",
					"pinyin": "handan",
					"first_letters": "HDS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "77",
					"name": "邢台市",
					"letter": "X",
					"pinyin": "xingtai",
					"first_letters": "XTS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "78",
					"name": "保定市",
					"letter": "B",
					"pinyin": "baoding",
					"first_letters": "BDS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "79",
					"name": "张家口市",
					"letter": "Z",
					"pinyin": "zhangjiakou",
					"first_letters": "ZJKS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "80",
					"name": "承德市",
					"letter": "C",
					"pinyin": "chengde",
					"first_letters": "CDS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "81",
					"name": "衡水市",
					"letter": "H",
					"pinyin": "hengshui",
					"first_letters": "HSS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "82",
					"name": "廊坊市",
					"letter": "L",
					"pinyin": "langfang",
					"first_letters": "LFS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}, {
					"id": "83",
					"name": "沧州市",
					"letter": "C",
					"pinyin": "cangzhou",
					"first_letters": "CZS",
					"upid": "3",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "27",
				"name": "陕西",
				"letter": "S",
				"pinyin": "shanxi27",
				"first_letters": "SXS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "陕西省",
				"son": [{
					"id": "27",
					"name": "陕西省",
					"letter": "S",
					"pinyin": "shanxi27",
					"first_letters": "SXS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "陕西省"
				}, {
					"id": "438",
					"name": "西安市",
					"letter": "X",
					"pinyin": "xian",
					"first_letters": "XAS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "440",
					"name": "宝鸡市",
					"letter": "B",
					"pinyin": "baoji",
					"first_letters": "BJS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "441",
					"name": "咸阳市",
					"letter": "X",
					"pinyin": "xianyang",
					"first_letters": "XYS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "444",
					"name": "汉中市",
					"letter": "H",
					"pinyin": "hanzhong",
					"first_letters": "HZS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "442",
					"name": "渭南市",
					"letter": "W",
					"pinyin": "weinan",
					"first_letters": "WNS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "443",
					"name": "延安市",
					"letter": "Y",
					"pinyin": "yanan",
					"first_letters": "YAS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "445",
					"name": "榆林市",
					"letter": "Y",
					"pinyin": "yulin445",
					"first_letters": "YLS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}, {
					"id": "446",
					"name": "安康市",
					"letter": "A",
					"pinyin": "ankang",
					"first_letters": "AKS",
					"upid": "27",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "12",
				"name": "安徽",
				"letter": "A",
				"pinyin": "anhui",
				"first_letters": "AHS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "安徽省",
				"son": [{
					"id": "12",
					"name": "安徽省",
					"letter": "A",
					"pinyin": "anhui",
					"first_letters": "AHS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "安徽省"
				}, {
					"id": "186",
					"name": "合肥市",
					"letter": "H",
					"pinyin": "hefei",
					"first_letters": "HFS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "187",
					"name": "芜湖市",
					"letter": "W",
					"pinyin": "wuhu",
					"first_letters": "WHS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "188",
					"name": "蚌埠市",
					"letter": "B",
					"pinyin": "bengbu",
					"first_letters": "BBS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "189",
					"name": "淮南市",
					"letter": "H",
					"pinyin": "huainan",
					"first_letters": "HNS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "190",
					"name": "马鞍山市",
					"letter": "M",
					"pinyin": "maanshan",
					"first_letters": "MASS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "191",
					"name": "淮北市",
					"letter": "H",
					"pinyin": "huaibei",
					"first_letters": "HBS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "192",
					"name": "铜陵市",
					"letter": "T",
					"pinyin": "tongling",
					"first_letters": "TLS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "193",
					"name": "安庆市",
					"letter": "A",
					"pinyin": "anqing",
					"first_letters": "AQS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "195",
					"name": "滁州市",
					"letter": "C",
					"pinyin": "chuzhou",
					"first_letters": "CZS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "196",
					"name": "阜阳市",
					"letter": "F",
					"pinyin": "fuyang",
					"first_letters": "FYS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "197",
					"name": "宿州市",
					"letter": "S",
					"pinyin": "suzhou197",
					"first_letters": "SZS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "199",
					"name": "六安市",
					"letter": "L",
					"pinyin": "liuan",
					"first_letters": "LAS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "200",
					"name": "亳州市",
					"letter": "H",
					"pinyin": "bozhou",
					"first_letters": "HZS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "201",
					"name": "池州市",
					"letter": "C",
					"pinyin": "chizhou",
					"first_letters": "CZS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}, {
					"id": "202",
					"name": "宣城市",
					"letter": "X",
					"pinyin": "xuancheng",
					"first_letters": "XCS",
					"upid": "12",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "14",
				"name": "江西",
				"letter": "J",
				"pinyin": "jiangxi",
				"first_letters": "JXS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "江西省",
				"son": [{
					"id": "14",
					"name": "江西省",
					"letter": "J",
					"pinyin": "jiangxi",
					"first_letters": "JXS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "江西省"
				}, {
					"id": "212",
					"name": "南昌市",
					"letter": "N",
					"pinyin": "nanchang",
					"first_letters": "NCS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "213",
					"name": "景德镇市",
					"letter": "J",
					"pinyin": "jingdezhen",
					"first_letters": "JDZS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "214",
					"name": "萍乡市",
					"letter": "P",
					"pinyin": "pingxiang",
					"first_letters": "PXS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "215",
					"name": "九江市",
					"letter": "J",
					"pinyin": "jiujiang",
					"first_letters": "JJS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "216",
					"name": "新余市",
					"letter": "X",
					"pinyin": "xinyu",
					"first_letters": "XYS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "217",
					"name": "鹰潭市",
					"letter": "Y",
					"pinyin": "yingtan",
					"first_letters": "YTS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "218",
					"name": "赣州市",
					"letter": "G",
					"pinyin": "ganzhou",
					"first_letters": "GZS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "219",
					"name": "吉安市",
					"letter": "J",
					"pinyin": "jian",
					"first_letters": "JAS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "220",
					"name": "宜春市",
					"letter": "Y",
					"pinyin": "yichun220",
					"first_letters": "YCS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "221",
					"name": "抚州市",
					"letter": "F",
					"pinyin": "fuzhou221",
					"first_letters": "FZS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}, {
					"id": "222",
					"name": "上饶市",
					"letter": "S",
					"pinyin": "shangrao",
					"first_letters": "SRS",
					"upid": "14",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "25",
				"name": "云南",
				"letter": "Y",
				"pinyin": "yunnan",
				"first_letters": "YNS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "云南省",
				"son": [{
					"id": "25",
					"name": "云南省",
					"letter": "Y",
					"pinyin": "yunnan",
					"first_letters": "YNS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "云南省"
				}, {
					"id": "415",
					"name": "昆明市",
					"letter": "K",
					"pinyin": "kunming",
					"first_letters": "KMS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "416",
					"name": "曲靖市",
					"letter": "Q",
					"pinyin": "qujing",
					"first_letters": "QJS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "417",
					"name": "玉溪市",
					"letter": "Y",
					"pinyin": "yuxi",
					"first_letters": "YXS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "418",
					"name": "保山市",
					"letter": "B",
					"pinyin": "baoshan",
					"first_letters": "BSS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "419",
					"name": "昭通市",
					"letter": "Z",
					"pinyin": "zhaotong",
					"first_letters": "ZTS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "420",
					"name": "丽江市",
					"letter": "L",
					"pinyin": "lijiang",
					"first_letters": "LJS",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "423",
					"name": "楚雄彝族自治州",
					"letter": "C",
					"pinyin": "chuxiong",
					"first_letters": "CXYZZZZ",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "424",
					"name": "红河哈尼族彝族自治州",
					"letter": "H",
					"pinyin": "honghe",
					"first_letters": "HHHNZYZZZZ",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "425",
					"name": "文山壮族苗族自治州",
					"letter": "W",
					"pinyin": "wenshan",
					"first_letters": "WSZZMZZZZ",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "426",
					"name": "西双版纳傣族自治州",
					"letter": "X",
					"pinyin": "xishuangbanna",
					"first_letters": "XSBNDZZZZ",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}, {
					"id": "427",
					"name": "大理白族自治州",
					"letter": "D",
					"pinyin": "dali",
					"first_letters": "DLBZZZZ",
					"upid": "25",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "8",
				"name": "黑龙江",
				"letter": "H",
				"pinyin": "heilongjiang",
				"first_letters": "HLJS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "黑龙江省",
				"son": [{
					"id": "8",
					"name": "黑龙江省",
					"letter": "H",
					"pinyin": "heilongjiang",
					"first_letters": "HLJS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "黑龙江省"
				}, {
					"id": "130",
					"name": "哈尔滨市",
					"letter": "H",
					"pinyin": "haerbin",
					"first_letters": "HEBS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "131",
					"name": "齐齐哈尔市",
					"letter": "Q",
					"pinyin": "qiqihaer",
					"first_letters": "QQHES",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "132",
					"name": "鸡西市",
					"letter": "J",
					"pinyin": "jixi",
					"first_letters": "JXS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "133",
					"name": "鹤岗市",
					"letter": "H",
					"pinyin": "hegang",
					"first_letters": "HGS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "135",
					"name": "大庆市",
					"letter": "D",
					"pinyin": "daqing",
					"first_letters": "DQS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "137",
					"name": "佳木斯市",
					"letter": "J",
					"pinyin": "jiamusi",
					"first_letters": "JMSS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "138",
					"name": "七台河市",
					"letter": "Q",
					"pinyin": "qitaihe",
					"first_letters": "QTHS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "139",
					"name": "牡丹江市",
					"letter": "M",
					"pinyin": "mudanjiang",
					"first_letters": "MDJS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}, {
					"id": "141",
					"name": "绥化市",
					"letter": "S",
					"pinyin": "suihua",
					"first_letters": "SHS",
					"upid": "8",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "4",
				"name": "山西",
				"letter": "S",
				"pinyin": "shanxi4",
				"first_letters": "SXS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "山西省",
				"son": [{
					"id": "4",
					"name": "山西省",
					"letter": "S",
					"pinyin": "shanxi4",
					"first_letters": "SXS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "山西省"
				}, {
					"id": "84",
					"name": "太原市",
					"letter": "T",
					"pinyin": "taiyuan",
					"first_letters": "TYS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "90",
					"name": "晋中市",
					"letter": "J",
					"pinyin": "jinzhong",
					"first_letters": "JZS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "91",
					"name": "运城市",
					"letter": "Y",
					"pinyin": "yuncheng",
					"first_letters": "YCS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "85",
					"name": "大同市",
					"letter": "D",
					"pinyin": "datong",
					"first_letters": "DTS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "86",
					"name": "阳泉市",
					"letter": "Y",
					"pinyin": "yangquan",
					"first_letters": "YQS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "87",
					"name": "长治市",
					"letter": "C",
					"pinyin": "changzhi",
					"first_letters": "CZS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "88",
					"name": "晋城市",
					"letter": "J",
					"pinyin": "jincheng",
					"first_letters": "JCS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "89",
					"name": "朔州市",
					"letter": "S",
					"pinyin": "shuozhou",
					"first_letters": "SZS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}, {
					"id": "93",
					"name": "临汾市",
					"letter": "L",
					"pinyin": "linfen",
					"first_letters": "LFS",
					"upid": "4",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "20",
				"name": "广西壮族自治区",
				"letter": "G",
				"pinyin": "guangxi",
				"first_letters": "GXZZZZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "广西壮族自治区",
				"son": [{
					"id": "20",
					"name": "广西壮族自治区",
					"letter": "G",
					"pinyin": "guangxi",
					"first_letters": "GXZZZZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "广西壮族自治区"
				}, {
					"id": "310",
					"name": "南宁市",
					"letter": "N",
					"pinyin": "nanning",
					"first_letters": "NNS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "311",
					"name": "柳州市",
					"letter": "L",
					"pinyin": "liuzhou",
					"first_letters": "LZS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "312",
					"name": "桂林市",
					"letter": "G",
					"pinyin": "guilin",
					"first_letters": "GLS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "313",
					"name": "梧州市",
					"letter": "W",
					"pinyin": "wuzhou",
					"first_letters": "WZS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "314",
					"name": "北海市",
					"letter": "B",
					"pinyin": "beihai",
					"first_letters": "BHS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "315",
					"name": "防城港市",
					"letter": "F",
					"pinyin": "fangchenggang",
					"first_letters": "FCGS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "316",
					"name": "钦州市",
					"letter": "Q",
					"pinyin": "qinzhou",
					"first_letters": "QZS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "317",
					"name": "贵港市",
					"letter": "G",
					"pinyin": "guigang",
					"first_letters": "GGS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "318",
					"name": "玉林市",
					"letter": "Y",
					"pinyin": "yulin318",
					"first_letters": "YLS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "319",
					"name": "百色市",
					"letter": "B",
					"pinyin": "baise",
					"first_letters": "BSS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "320",
					"name": "贺州市",
					"letter": "H",
					"pinyin": "hezhou",
					"first_letters": "HZS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}, {
					"id": "322",
					"name": "来宾市",
					"letter": "L",
					"pinyin": "laibin",
					"first_letters": "LBS",
					"upid": "20",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "7",
				"name": "吉林",
				"letter": "J",
				"pinyin": "jilin",
				"first_letters": "JLS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "吉林省",
				"son": [{
					"id": "7",
					"name": "吉林省",
					"letter": "J",
					"pinyin": "jilin",
					"first_letters": "JLS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "吉林省"
				}, {
					"id": "121",
					"name": "长春市",
					"letter": "C",
					"pinyin": "changchun",
					"first_letters": "CCS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "122",
					"name": "吉林市",
					"letter": "J",
					"pinyin": "jilin122",
					"first_letters": "JLS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "123",
					"name": "四平市",
					"letter": "S",
					"pinyin": "siping",
					"first_letters": "SPS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "125",
					"name": "通化市",
					"letter": "T",
					"pinyin": "tonghua",
					"first_letters": "THS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "126",
					"name": "白山市",
					"letter": "B",
					"pinyin": "baishan",
					"first_letters": "BSS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "127",
					"name": "松原市",
					"letter": "S",
					"pinyin": "songyuan",
					"first_letters": "SYS",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}, {
					"id": "129",
					"name": "延边朝鲜族自治州",
					"letter": "Y",
					"pinyin": "yanbian",
					"first_letters": "YBCXZZZZ",
					"upid": "7",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "21",
				"name": "海南",
				"letter": "H",
				"pinyin": "hainan",
				"first_letters": "HNS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "海南省",
				"son": [{
					"id": "21",
					"name": "海南省",
					"letter": "H",
					"pinyin": "hainan",
					"first_letters": "HNS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "海南省"
				}, {
					"id": "324",
					"name": "海口市",
					"letter": "H",
					"pinyin": "haikou",
					"first_letters": "HKS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "325",
					"name": "三亚市",
					"letter": "S",
					"pinyin": "sanya",
					"first_letters": "SYS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "327",
					"name": "琼海市",
					"letter": "Q",
					"pinyin": "qionghai",
					"first_letters": "QHS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "328",
					"name": "儋州市",
					"letter": "",
					"pinyin": "danzhou328",
					"first_letters": "ZS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "329",
					"name": "文昌市",
					"letter": "W",
					"pinyin": "wenchang",
					"first_letters": "WCS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "330",
					"name": "万宁市",
					"letter": "W",
					"pinyin": "wanning",
					"first_letters": "WNS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "331",
					"name": "东方市",
					"letter": "D",
					"pinyin": "dongfang",
					"first_letters": "DFS",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}, {
					"id": "339",
					"name": "陵水黎族自治县",
					"letter": "L",
					"pinyin": "lingshui",
					"first_letters": "LSLZZZX",
					"upid": "21",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "5",
				"name": "内蒙古自治区",
				"letter": "N",
				"pinyin": "neimeng",
				"first_letters": "NMGZZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "内蒙古自治区",
				"son": [{
					"id": "5",
					"name": "内蒙古自治区",
					"letter": "N",
					"pinyin": "neimeng",
					"first_letters": "NMGZZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "内蒙古自治区"
				}, {
					"id": "95",
					"name": "呼和浩特市",
					"letter": "H",
					"pinyin": "huhehaote",
					"first_letters": "HHHTS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "96",
					"name": "包头市",
					"letter": "B",
					"pinyin": "baotou",
					"first_letters": "BTS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "98",
					"name": "赤峰市",
					"letter": "C",
					"pinyin": "chifeng",
					"first_letters": "CFS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "99",
					"name": "通辽市",
					"letter": "T",
					"pinyin": "tongliao",
					"first_letters": "TLS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "100",
					"name": "鄂尔多斯市",
					"letter": "E",
					"pinyin": "eerduosi",
					"first_letters": "EEDSS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "101",
					"name": "呼伦贝尔市",
					"letter": "H",
					"pinyin": "hulunbeier",
					"first_letters": "HLBES",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "102",
					"name": "巴彦淖尔市",
					"letter": "B",
					"pinyin": "bayannaoer",
					"first_letters": "BYNES",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "103",
					"name": "乌兰察布市",
					"letter": "W",
					"pinyin": "wulanchabu",
					"first_letters": "WLCBS",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "104",
					"name": "兴安盟",
					"letter": "X",
					"pinyin": "xinganmeng",
					"first_letters": "XAM",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}, {
					"id": "105",
					"name": "锡林郭勒盟",
					"letter": "X",
					"pinyin": "xilinguole",
					"first_letters": "XLGLM",
					"upid": "5",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "24",
				"name": "贵州",
				"letter": "G",
				"pinyin": "guizhou",
				"first_letters": "GZS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "贵州省",
				"son": [{
					"id": "24",
					"name": "贵州省",
					"letter": "G",
					"pinyin": "guizhou",
					"first_letters": "GZS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "贵州省"
				}, {
					"id": "406",
					"name": "贵阳市",
					"letter": "G",
					"pinyin": "guiyang",
					"first_letters": "GYS",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "408",
					"name": "遵义市",
					"letter": "Z",
					"pinyin": "zunyi",
					"first_letters": "ZYS",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "407",
					"name": "六盘水市",
					"letter": "L",
					"pinyin": "liupanshui",
					"first_letters": "LPSS",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "410",
					"name": "铜仁地区",
					"letter": "T",
					"pinyin": "tongren",
					"first_letters": "TRDQ",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "411",
					"name": "黔西南布依族苗族自治州",
					"letter": "Q",
					"pinyin": "qianxinan",
					"first_letters": "QXNBYZMZZZZ",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "412",
					"name": "毕节地区",
					"letter": "B",
					"pinyin": "bijie",
					"first_letters": "BJDQ",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "413",
					"name": "黔东南苗族侗族自治州",
					"letter": "Q",
					"pinyin": "qiandongnan",
					"first_letters": "QDNMZDZZZZ",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}, {
					"id": "414",
					"name": "黔南布依族苗族自治州",
					"letter": "Q",
					"pinyin": "qiannan",
					"first_letters": "QNBYZMZZZZ",
					"upid": "24",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "26",
				"name": "西藏自治区",
				"letter": "X",
				"pinyin": "xizang",
				"first_letters": "XCZZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "西藏自治区",
				"son": [{
					"id": "26",
					"name": "西藏自治区",
					"letter": "X",
					"pinyin": "xizang",
					"first_letters": "XCZZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "西藏自治区"
				}, {
					"id": "433",
					"name": "山南市",
					"letter": "S",
					"pinyin": "shannan",
					"first_letters": "SNS",
					"upid": "26",
					"level": "2",
					"selected": "0"
				}, {
					"id": "437",
					"name": "林芝市",
					"letter": "L",
					"pinyin": "linzhi",
					"first_letters": "LZS",
					"upid": "26",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "31",
				"name": "新疆维吾尔自治区",
				"letter": "X",
				"pinyin": "xinjiang",
				"first_letters": "XJWWEZZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "新疆维吾尔自治区",
				"son": [{
					"id": "31",
					"name": "新疆维吾尔自治区",
					"letter": "X",
					"pinyin": "xinjiang",
					"first_letters": "XJWWEZZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "新疆维吾尔自治区"
				}, {
					"id": "475",
					"name": "乌鲁木齐市",
					"letter": "W",
					"pinyin": "wulumuqi",
					"first_letters": "WLMQS",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}, {
					"id": "478",
					"name": "哈密地区",
					"letter": "H",
					"pinyin": "hami",
					"first_letters": "HMDQ",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}, {
					"id": "479",
					"name": "昌吉回族自治州",
					"letter": "C",
					"pinyin": "changji",
					"first_letters": "CJHZZZZ",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}, {
					"id": "481",
					"name": "巴音郭楞蒙古自治州",
					"letter": "B",
					"pinyin": "bayinguole",
					"first_letters": "BYGLMGZZZ",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}, {
					"id": "486",
					"name": "伊犁哈萨克自治州",
					"letter": "Y",
					"pinyin": "yili",
					"first_letters": "YLHSKZZZ",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}, {
					"id": "489",
					"name": "石河子市",
					"letter": "S",
					"pinyin": "shihezi",
					"first_letters": "SHZS",
					"upid": "31",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "28",
				"name": "甘肃",
				"letter": "G",
				"pinyin": "gansu",
				"first_letters": "GSS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "甘肃省",
				"son": [{
					"id": "28",
					"name": "甘肃省",
					"letter": "G",
					"pinyin": "gansu",
					"first_letters": "GSS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "甘肃省"
				}, {
					"id": "448",
					"name": "兰州市",
					"letter": "L",
					"pinyin": "lanzhou",
					"first_letters": "LZS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "451",
					"name": "白银市",
					"letter": "B",
					"pinyin": "baiyin",
					"first_letters": "BYS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "454",
					"name": "张掖市",
					"letter": "Z",
					"pinyin": "zhangye",
					"first_letters": "ZYS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "455",
					"name": "平凉市",
					"letter": "P",
					"pinyin": "pingliang",
					"first_letters": "PLS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "456",
					"name": "酒泉市",
					"letter": "J",
					"pinyin": "jiuquan",
					"first_letters": "JQS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "457",
					"name": "庆阳市",
					"letter": "Q",
					"pinyin": "qingyang",
					"first_letters": "QYS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}, {
					"id": "459",
					"name": "陇南市",
					"letter": "L",
					"pinyin": "longnan",
					"first_letters": "LNS",
					"upid": "28",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "29",
				"name": "青海",
				"letter": "Q",
				"pinyin": "qinghai",
				"first_letters": "QHS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "青海省",
				"son": [{
					"id": "29",
					"name": "青海省",
					"letter": "Q",
					"pinyin": "qinghai",
					"first_letters": "QHS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "青海省"
				}, {
					"id": "462",
					"name": "西宁市",
					"letter": "X",
					"pinyin": "xining",
					"first_letters": "XNS",
					"upid": "29",
					"level": "2",
					"selected": "0"
				}, {
					"id": "469",
					"name": "海西蒙古族藏族自治州",
					"letter": "H",
					"pinyin": "haixi",
					"first_letters": "HXMGZCZZZZ",
					"upid": "29",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "30",
				"name": "宁夏回族自治区",
				"letter": "N",
				"pinyin": "ningxia",
				"first_letters": "NXHZZZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "宁夏回族自治区",
				"son": [{
					"id": "30",
					"name": "宁夏回族自治区",
					"letter": "N",
					"pinyin": "ningxia",
					"first_letters": "NXHZZZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "宁夏回族自治区"
				}, {
					"id": "470",
					"name": "银川市",
					"letter": "Y",
					"pinyin": "yinchuan",
					"first_letters": "YCS",
					"upid": "30",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "32",
				"name": "台湾",
				"letter": "T",
				"pinyin": "taiwan",
				"first_letters": "TWS",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "台湾",
				"son": [{
					"id": "32",
					"name": "台湾",
					"letter": "T",
					"pinyin": "taiwan",
					"first_letters": "TWS",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "台湾"
				}, {
					"id": "493",
					"name": "台北市",
					"letter": "T",
					"pinyin": "taibei",
					"first_letters": "TBS",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "494",
					"name": "高雄市",
					"letter": "G",
					"pinyin": "gaoxiong",
					"first_letters": "GXS",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "496",
					"name": "台中市",
					"letter": "T",
					"pinyin": "taizhong",
					"first_letters": "TZS",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "498",
					"name": "新竹市",
					"letter": "X",
					"pinyin": "xinzhu",
					"first_letters": "XZS",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "500",
					"name": "台北县",
					"letter": "T",
					"pinyin": "taibeixian",
					"first_letters": "TBX",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "502",
					"name": "桃园县",
					"letter": "T",
					"pinyin": "taoyuanxian",
					"first_letters": "TYX",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "510",
					"name": "台南县",
					"letter": "T",
					"pinyin": "tainanxian",
					"first_letters": "TNX",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}, {
					"id": "45070",
					"name": "新北市",
					"letter": "",
					"pinyin": "xinbei",
					"first_letters": "XBS",
					"upid": "32",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "33",
				"name": "香港特别行政区",
				"letter": "X",
				"pinyin": "xianggang",
				"first_letters": "XGTBXZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "香港特别行政区",
				"son": [{
					"id": "33",
					"name": "香港特别行政区",
					"letter": "X",
					"pinyin": "xianggang",
					"first_letters": "XGTBXZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "香港特别行政区"
				}, {
					"id": "516",
					"name": "中西区",
					"letter": "",
					"pinyin": "zhongxiqu",
					"first_letters": "ZXQ",
					"upid": "33",
					"level": "2",
					"selected": "0"
				}, {
					"id": "518",
					"name": "九龙城区",
					"letter": "",
					"pinyin": "jiulongchengqu",
					"first_letters": "JLCQ",
					"upid": "33",
					"level": "2",
					"selected": "0"
				}, {
					"id": "521",
					"name": "深水埗区",
					"letter": "",
					"pinyin": "shenshuibuqu",
					"first_letters": "SSBQ",
					"upid": "33",
					"level": "2",
					"selected": "0"
				}, {
					"id": "523",
					"name": "湾仔区",
					"letter": "",
					"pinyin": "wanzaiqu",
					"first_letters": "WZQ",
					"upid": "33",
					"level": "2",
					"selected": "0"
				}, {
					"id": "524",
					"name": "油尖旺区",
					"letter": "",
					"pinyin": "youjianwangqu",
					"first_letters": "YJWQ",
					"upid": "33",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "34",
				"name": "澳门特别行政区",
				"letter": "A",
				"pinyin": "aomen34",
				"first_letters": "AMTBXZQ",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "澳门特别行政区",
				"son": [{
					"id": "34",
					"name": "澳门特别行政区",
					"letter": "A",
					"pinyin": "aomen34",
					"first_letters": "AMTBXZQ",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "澳门特别行政区"
				}]
			}, {
				"id": "35",
				"name": "海外",
				"letter": "H",
				"pinyin": "haiwai",
				"first_letters": "HW",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "海外",
				"son": [{
					"id": "556",
					"name": "韩国",
					"letter": "H",
					"pinyin": "hanguo",
					"first_letters": "HG",
					"upid": "35",
					"level": "2",
					"selected": "0"
				}, {
					"id": "557",
					"name": "新加坡",
					"letter": "X",
					"pinyin": "xinjiapo",
					"first_letters": "XJP",
					"upid": "35",
					"level": "2",
					"selected": "0"
				}, {
					"id": "560",
					"name": "泰国",
					"letter": "T",
					"pinyin": "taiguo",
					"first_letters": "TG",
					"upid": "35",
					"level": "2",
					"selected": "0"
				}, {
					"id": "561",
					"name": "日本",
					"letter": "R",
					"pinyin": "riben",
					"first_letters": "RB",
					"upid": "35",
					"level": "2",
					"selected": "0"
				}]
			}, {
				"id": "36",
				"name": "其他",
				"letter": "Q",
				"pinyin": "qita",
				"first_letters": "QT",
				"upid": "45052",
				"level": "1",
				"selected": "0",
				"allname": "其他",
				"son": [{
					"id": "36",
					"name": "其他",
					"letter": "Q",
					"pinyin": "qita",
					"first_letters": "QT",
					"upid": "45052",
					"level": "1",
					"selected": "0",
					"allname": "其他"
				}]
			}
		]	
}
module.exports = {
	location_json : json
}